name = "website-homelabs"
type = "javascript"
main = "dist/_worker.js/index.js"
compatibility_date = "2025-09-03"

[[d1_databases]]
binding = "DB"
database_name = "homelabs-db"
database_id = "2a4aaf6d-1a0b-4f57-bdfc-9d7f8e2a1f1d"

[[kv_namespaces]]
binding = "website-homelabs"
id = "2b52709ad66d4e23a9846d50fabba585"

[env.staging]
main = "dist/_worker.js/index.js"

[env.production]
main = "dist/_worker.js/index.js"
